title: Blog zu Bibliotheks- und Archivinformatik
author: Martina Z.
description: Lerntagebuch über den Kurs Bibliotheks- und Archivinformatik 2024

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
